mutation MyMutation {
	insert_users(
		objects: {
			birthday: "2000-01-01"
			displayed_name: "Kasia"
			nick: "kasia"
		}
	) {
		affected_rows
		returning {
			id
			nick
			displayed_name
			birthday
		}
	}
}


//response:
{
	"data": {
		"insert_users": {
			"affected_rows": 1,
			"returning": [
				{
					"id": 5,
					"nick": "kasia",
					"displayed_name": "Kasia",
					"birthday": "2000-01-01"
				}
			]
		}
	}
}